'use client';

import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import { Sparkles, CheckCircle2, Lightbulb, ArrowRight, Loader2, Download, RotateCw } from 'lucide-react';
import { useGuest } from '@/components/providers/GuestContext';

interface AnalysisResult {
  score: number;
  ats_score?: number;
  verdict?: string;
  score_breakdown?: {
    structure: string;
    skills: string;
    experience: string;
    impact: string;
    professionalism: string;
  };
  deductions?: string[];
  strengths: string[];
  cons?: string[];
  improvements: string[];
}

export default function ResumeAnalysis() {
  const [resumeText, setResumeText] = useState('');
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const { isGuest } = useGuest();

  useEffect(() => {
    const checkExisting = async () => {
      if (isGuest) return; // Guests start fresh

      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return;

      const { data } = await supabase
        .from('resumes')
        .select('*')
        .eq('user_id', session.user.id)
        .order('created_at', { ascending: false })
        .limit(1)
        .single();

      if (data) {
        setResult(data.ai_feedback);
        setResumeText(data.resume_text || '');
      }
    };
    checkExisting();
  }, [isGuest]);

  const handleAnalyze = async () => {
    if (!resumeText.trim()) return;
    setAnalyzing(true);
    setError(null);

    try {
      let headers = {};
      let userId = '';

      if (isGuest) {
        userId = 'guest';
        headers = { 'Content-Type': 'application/json' };
      } else {
        const { data: { session } } = await supabase.auth.getSession();
        if (!session) throw new Error("Not authenticated");
        userId = session.user.id;
        headers = {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`
        };
      }

      const response = await fetch('/api/analyze-resume', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          resumeText,
          userId
        })
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Analysis failed');

      setResult(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setAnalyzing(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!result) return;

    // Create full ATS report content
    const breakdownText = result.score_breakdown ? `
SCORE BREAKDOWN:
  Structure:      ${result.score_breakdown.structure}
  Skills:         ${result.score_breakdown.skills}
  Experience:     ${result.score_breakdown.experience}
  Impact:         ${result.score_breakdown.impact}
  Professionalism: ${result.score_breakdown.professionalism}
` : '';

    const deductionsText = result.deductions && result.deductions.length > 0 ? `
DEDUCTIONS APPLIED:
${result.deductions.map(d => `  • ${d}`).join('\n')}
` : '';

    const consText = result.cons && result.cons.length > 0 ? `
CONS (ATS GAPS):
${result.cons.map((c, i) => `${i + 1}. ${c}`).join('\n')}
` : '';

    const pdfContent = `
═══════════════════════════════════════════════════════
           RESUME ANALYSIS REPORT
           Generated by SkillSync-ai
           ${new Date().toLocaleDateString()}
═══════════════════════════════════════════════════════

ATS SCORE: ${result.score}/100
VERDICT:   ${result.verdict || 'N/A'}

${breakdownText}
${deductionsText}
───────────────────────────────────────────────────────
STRENGTHS:
${result.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${consText}
───────────────────────────────────────────────────────
IMPROVEMENTS (ACTION ITEMS):
${result.improvements.map((imp, i) => `${i + 1}. ${imp}`).join('\n')}

═══════════════════════════════════════════════════════
RESUME CONTENT:
═══════════════════════════════════════════════════════
${resumeText}

───────────────────────────────────────────────────────
Note: Scores reflect ATS screening + recruiter shortlisting bias.
    `.trim();

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ats-resume-report-${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Results Section (if available) */}
      {result && (
        <div className="bg-[var(--bg-secondary)] border border-[var(--border-subtle)] rounded-xl p-8 relative overflow-hidden group animate-fade-in-up">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-[var(--green-500)] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

          {/* Header with Actions */}
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-[rgba(62,207,142,0.1)] text-[var(--green-500)]">
                <Sparkles size={20} />
              </div>
              <h3 className="text-lg font-bold text-white">Analysis Results</h3>
            </div>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => {
                  console.log('Download clicked');
                  handleDownloadPDF();
                }}
                className="px-4 py-2 text-sm font-medium text-[var(--text-secondary)] hover:text-white bg-[var(--bg-tertiary)] rounded-lg hover:bg-[var(--bg-elevated)] transition-all border border-[var(--border-subtle)] hover:border-[var(--border-medium)] flex items-center gap-2 active:scale-95"
              >
                <Download size={16} />
                Download
              </button>
              <button
                type="button"
                onClick={() => {
                  console.log('Re-analyze clicked');
                  handleAnalyze();
                }}
                disabled={analyzing || !resumeText.trim()}
                className="px-4 py-2 text-sm font-medium bg-[var(--green-500)] text-white rounded-lg hover:bg-[var(--green-600)] transition-all flex items-center gap-2 disabled:opacity-50 active:scale-95"
              >
                <RotateCw size={16} className={analyzing ? 'animate-spin' : ''} />
                {analyzing ? 'Analyzing...' : 'Re-analyze'}
              </button>
            </div>
          </div>

          {/* Score Section */}
          <div className="flex items-start gap-6 mb-8">
            <div className="relative w-24 h-24 flex items-center justify-center flex-shrink-0">
              <svg className="w-full h-full transform -rotate-90">
                <circle
                  cx="48"
                  cy="48"
                  r="42"
                  stroke="var(--bg-tertiary)"
                  strokeWidth="8"
                  fill="transparent"
                />
                <circle
                  cx="48"
                  cy="48"
                  r="42"
                  stroke={result.score >= 70 ? "var(--green-500)" : result.score >= 50 ? "var(--warning)" : "var(--error)"}
                  strokeWidth="8"
                  fill="transparent"
                  strokeDasharray={264}
                  strokeDashoffset={264 - (264 * result.score) / 100}
                  className="transition-all duration-1000 ease-out"
                />
              </svg>
              <span className="absolute text-2xl font-extrabold text-white">{result.score}</span>
            </div>
            
            <div className="flex-1">
              <div className="text-sm text-[var(--text-tertiary)] uppercase tracking-wide font-semibold mb-1">Overall Score</div>
              {result.verdict && (
                <div className={`text-lg font-bold mb-2 ${
                  result.score >= 80 ? 'text-[var(--green-500)]' : 
                  result.score >= 60 ? 'text-[var(--warning)]' : 
                  'text-[var(--error)]'
                }`}>
                  {result.verdict}
                </div>
              )}
              <p className="text-xs text-[var(--text-tertiary)] italic">
                Scores reflect ATS screening + recruiter shortlisting bias.
              </p>
            </div>
          </div>

          {/* Score Breakdown Section */}
          {result.score_breakdown && (
            <div className="mb-6 p-4 bg-[var(--bg-tertiary)] rounded-lg">
              <h4 className="text-sm font-bold text-white mb-4">Score Breakdown</h4>
              <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
                {[
                  { label: 'Structure', value: result.score_breakdown.structure },
                  { label: 'Skills', value: result.score_breakdown.skills },
                  { label: 'Experience', value: result.score_breakdown.experience },
                  { label: 'Impact', value: result.score_breakdown.impact },
                  { label: 'Professional', value: result.score_breakdown.professionalism },
                ].map((item) => (
                  <div key={item.label} className="text-center p-2 bg-[var(--bg-input)] rounded-lg">
                    <div className="text-xs text-[var(--text-tertiary)] mb-1">{item.label}</div>
                    <div className="text-sm font-bold text-[var(--green-500)]">{item.value}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Strengths (left) | Cons (right) */}
          <div className="grid md:grid-cols-2 gap-6 mb-6">
            {/* Strengths */}
            <div className="p-4 bg-[rgba(34,197,94,0.05)] border border-[rgba(34,197,94,0.2)] rounded-lg">
              <h4 className="flex items-center gap-2 text-sm font-bold text-white mb-3">
                <CheckCircle2 size={16} className="text-[var(--success)]" />
                Strengths
              </h4>
              <ul className="space-y-2">
                {result.strengths.map((str, i) => (
                  <li key={i} className="text-sm text-[var(--text-secondary)] flex items-start gap-2">
                    <span className="text-[var(--success)] mt-1">✓</span>
                    {str}
                  </li>
                ))}
              </ul>
            </div>

            {/* Cons (ATS Gaps) */}
            <div className="p-4 bg-[rgba(239,68,68,0.05)] border border-[rgba(239,68,68,0.2)] rounded-lg">
              <h4 className="flex items-center gap-2 text-sm font-bold text-white mb-3">
                <Lightbulb size={16} className="text-[var(--error)]" />
                Cons (ATS Gaps)
              </h4>
              <ul className="space-y-2">
                {(result.cons || []).map((con, i) => (
                  <li key={i} className="text-sm text-[var(--text-secondary)] flex items-start gap-2">
                    <span className="text-[var(--error)] mt-1">✗</span>
                    {con}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Improvements (full width) */}
          <div className="p-4 bg-[rgba(234,179,8,0.05)] border border-[rgba(234,179,8,0.2)] rounded-lg">
            <h4 className="flex items-center gap-2 text-sm font-bold text-white mb-3">
              <ArrowRight size={16} className="text-[var(--warning)]" />
              Improvements
            </h4>
            <div className="grid md:grid-cols-2 gap-x-6 gap-y-2">
              {result.improvements.map((imp, i) => (
                <div key={i} className="text-sm text-[var(--text-secondary)] flex items-start gap-2">
                  <span className="text-[var(--warning)] mt-0.5">→</span>
                  {imp}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Resume Input Section (always visible) */}
      <div className="bg-[var(--bg-secondary)] border border-[var(--border-subtle)] rounded-xl p-8 relative overflow-hidden group">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-[var(--green-500)] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 rounded-lg bg-[rgba(62,207,142,0.1)] text-[var(--green-500)]">
            <Sparkles size={20} />
          </div>
          <h3 className="text-lg font-bold text-white">Resume Content</h3>
        </div>
        
        <div className="space-y-6">
          <div className="relative">
            <textarea
              value={resumeText}
              onChange={(e) => setResumeText(e.target.value)}
              placeholder="Paste your resume text here..."
              className="w-full h-[240px] p-4 bg-[var(--bg-input)] border border-[var(--border-medium)] rounded-xl focus:ring-1 focus:ring-[var(--green-500)] focus:border-[var(--green-500)] focus:outline-none resize-none text-sm text-[var(--text-secondary)] placeholder-[var(--text-disabled)] font-mono transition-all"
            />
            <div className="absolute bottom-3 right-3 text-[10px] text-[var(--text-disabled)] uppercase tracking-wider font-semibold">
              AI Powered
            </div>
          </div>
          
          {error && (
            <div className="text-sm text-[var(--error)] bg-[rgba(239,68,68,0.1)] p-3 rounded-lg border border-[rgba(239,68,68,0.2)]">
              {error}
            </div>
          )}
          
          {!result && (
            <button
              onClick={handleAnalyze}
              disabled={analyzing || resumeText.length < 50}
              className="w-full bg-gradient-to-r from-[var(--green-500)] to-[var(--green-600)] text-white p-4 rounded-lg text-sm font-bold flex items-center justify-center gap-2 hover:translate-y-[-2px] hover:shadow-[0_4px_20px_rgba(62,207,142,0.3)] transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:translate-y-0 disabled:hover:shadow-none"
            >
              {analyzing ? (
                <>
                  <Loader2 size={18} className="animate-spin" />
                  Analyzing...
                </>
              ) : (
                <>
                  Get AI Feedback
                  <ArrowRight size={18} />
                </>
              )}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
